### PR TITLE
Add translate button

### LINKED ISSUE #220: Easier method to contribute translations
Hi @Sneezry! I maintain the Firefox version of your add-on, and I wanted to see if you are interested in providing an easier way for people like @igorrhamon (#195) to contribute translations to this project. 

I got an [instance of Crowdin](https://crowdin.com/project/authenticator-firefox) approved for open source use, so if you wanted to we could link both versions of the extension to Crowdin and add a translate button to the extension. That way both Chrome and Firefox users could easily help translate the extension into other languages. 

Here's what it looks like in the Firefox version, if you are ok with it I'll submit a pull request here with the same changes and give you administrator access to the Crowdin instance. 

image

### PR DESCRIPTION
**Pull request by mymindstorm**
Closes #220

### CODE REVIEW

**Comment by ThePlenkov** [comment]
looks like your commit crashed everything.. the app doesn't work anymore

**Comment by mymindstorm** [comment]
Crap, I literally made a fix PR minutes after he accepted the main one but it looks like I was too late. Sorry

**Comment by MrFatoni** [comment]
i think error here
file **javascript/popup.js**
`+document.getElementById('menuTranslate').innerHTML += browser.i18n.getMessage('translate');`

**Comment by mymindstorm** [comment]
There is already a fix at #222 that just needs to be pushed.

**Comment by ThePlenkov** [comment]
image

**Comment by ThePlenkov** [comment]
there is no check on tabs length..

In my case tabs is empty.. so it means tab.url crashes.

I cannot blame the previous commit - as this popup.js fully belongs to the current one

**Pull request merged**
