### PR TITLE
Added check for format of the secret

### PR DESCRIPTION
**Pull request by preraksola**
Hi,
I have added a check for the format of the `secret` when the user adds a new account. It shows an alert if the `secret` is not it `Base32` or `Hex` format. I have implemented it using a `Regular Expression`.

I added this as per our conversation over #46 .

### CODE REVIEW

**Comment by Sneezry** [comment]
Thanks @preraksola ! Nice job!

However, some invalid secrets are detected failed:

zzzz8888
abcd012=

and some valid secrets are detected as invalid:

blz-abcd1234
bliz-abcd1234

blz- or bliz- are prefix for Battle.net account secrets.

**Comment by preraksola** [comment]
@Sneezry  I'll update the code accordingly.
Also, I did not consider the scenario of battle.net keys. Can you please let me know, what would be the string format for battle.net keys after `blz-` and `bliz-` prefix? Will be `Base32` or `HEX` or both?

**Comment by Sneezry** [comment]
It's Base32 :-)

**Comment by preraksola** [comment]
I have modified the code. You can test it now... :-)

**Comment by Sneezry** [comment]
Thanks Preraksola!

However, we can improve the code. For example, `return base32RegEx.test(secret) ? true : false;` can be changed to `return base32RegEx.test(secret);`, `/^((bliz-)|(blz-))/gi` can be changed to `/^(bliz-|blz-)/gi`.

Change

```
else if(checkSecret(secret, "hex"))
     {
 	    if(checkSecret(secret, "base32"))
...
```

to

```
else if(checkSecret(secret, 'hex') && checkSecret(secret, 'base32')) {
...
```

Also, `"` may be changed to `'` to be consistent, and put `{` to the same line of `if (xxx) `.

Could you please improve the code, thanks :-D

**Comment by preraksola** [comment]
Done ... :-)

**Pull request merged**
