### PR TITLE
Update popup.js

### PR DESCRIPTION
**Pull request by diposs**
it should work now

### CODE REVIEW

**Comment by ThePlenkov** [comment]
I made same trick in the console..
 For me it didn't work..

image

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by Sneezry** [comment]
I just didn't see this pr, and had updated the code to fix the issue. Thanks for the update. 4.20 has already uploaded to the market, and it should be available in one hour.

**Comment by ThePlenkov** [comment]
@Sneezry I did this trick manually in the console to get my passwords.. 

I added two lines.. 

the one - to fix browser => chrome issue..

But here on the snapshot above I also have crash as tabs is empty and it cannot access URL. I use russian if it can help.

So my second hook is push.tabs({url:""}) to skip the dump and get tokens

**Comment by Sneezry** [comment]
@ThePlenkov thanks for your suggestion, 4.20 is available in the market now, and the issue should be fixed by upgrading to the latest version.

**Pull request closed without merging**
